[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "container-orchestration-engine"
version = "0.1.0"
description = "Orchestry - "A lightweight container orchestration and clustering tool"
authors = [{name = "Manoj BR", email = "brmanoj461@gmail.com"}]
readme = "README.md"
requires-python = ">=3.10"
license = "GPL-3.0-or-later"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers", 
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "typer==0.17.4",
    "requests==2.32.5",
    "python-dotenv==1.1.1",
    "pyyaml==6.0.2",
    "platformdirs==4.4.0"
]

[tool.setuptools]
packages = [
    "cli"
]

[project.scripts]
orchestry = "cli.main:app"

[project.urls]
Homepage = "https://github.com/brmanoj461-dotcom/containerorchestration"
Repository =  "https://github.com/brmanoj461-dotcom/containerorchestration"
